#!/usr/bin/perl -w

# ----------------------
# $Log: xadmin,v $
# Revision 1.9  1997/10/28 16:36:29  turbo
# Instead of calling a separate function which does a exec, call the system()
# function in the buttons instead...
#
# Revision 1.8  1997/09/24 19:18:11  turbo
# Work on the Date/Time editor have begun... The GUI is done, but not the
#   functions...
#
# Revision 1.7  1997/09/24 16:54:10  turbo
# * Added the button 'Date/Time editor', disabled though...
# * Disabled the runlevel editor button..
#
# Revision 1.6  1997/08/16 19:12:40  turbo
# Undisabled the runlevel editors button...
#
# Revision 1.5  1997/08/03 17:42:46  turbo
# Made sure the last button got made, wasn't before...
#
# Revision 1.4  1997/04/26 21:36:54  turbo
# Removed the shadowed button for 'Network editor'.
#
# Revision 1.3  1997/04/19 23:14:58  turbo
# Added support for add/edit dns-entry
# Added support for add dns-domain
# Fixed bugg in size_string()
#
# Revision 1.2  1997/04/07 23:39:25  turbo
# Added support for 'DNS editor'.
#
# Revision 1.1  1997/03/29 04:08:12  turbo
# * Finaly got the 'Deactivate' and 'Reactivate' functions to work...
#   Also got the kreation of the home directory to work... (FINALY!!! :)
# * Cleaned up the GUI and fixed some small buggs, and added '-tearoff => 0'
#   to avoid the possibility to 'tearoff' a yes/no menu...
# * Added 'Edit quota for user' support.
#
# Revision 1.0.0.1  1997/03/12 02:10:44  turbo
# Initial release of 'XAdmin', a administration tool for X11.
# Needs perl and perl-tk. Made by Turbo Fredriksson <turbo@tripnet.se>
#

use Tk;
use Tk::ErrorDialog;
require "lib/xadmin.pl";

$bin_dir = "./bin";

# Are we running in a X enviroment?
# (Check if we have a DISPLAY variable)
if($ENV{'DISPLAY'}) {
    main();
    MainLoop;
} else {
    printf("Not running in a X enviroment...\n");
    exit 1;
}

# ----------------------
# main(void)
# This is the main routine...
sub main {
    # Create the main window...
    $window = MainWindow->new();

    # Configure the Main window...
    $window->title('System Maintainer');
    $window->iconname('System Maintainer');

    # Create some leading text...
    $msg = $window->Label(-font     => "-*-Helvetica-Medium-R-Normal--*-140-*-*-*-*-*-*",
			  -justify  => 'left',
			  -text     => "What action do you\nwant to preform?"
    );
    $msg->pack;

    # Create the Main buttons...
    main_buttons($window, 'main');

    # Create the frames...
    $buttons = $window->Frame;
    @pl = (-side   => 'top',
	   -expand => 1,
	   -padx   => '.1c',
	   -pady   => '.1c'
    );
    $buttons->pack(@pl);

    # Create the buttons...
    $butt{0} = $buttons->Button(-text       => 'User/Group editor',
				-width      => 14,
				-command    => sub{system("$bin_dir/xedit-users");}
    );
    $butt{1} = $buttons->Button(-text       => 'Domain editor',
				-width      => 14,
				-command    => sub{system("$bin_dir/xedit-dns");}
    );
    $butt{2} = $buttons->Button(-text       => 'Network editor',
				-width      => 14,
				-command    => sub{system("$bin_dir/xedit-net");}
    );
    $butt{3} = $buttons->Button(-text       => 'Runlevel editor',
				-width      => 14,
				-command    => sub{system("$bin_dir/xedit-runlvl");},
				-state      => 'disabled'
    );
    $butt{4} = $buttons->Button(-text       => 'File system editor',
				-width      => 14,
				-command    => sub{system("$bin_dir/xedit-fs");},
				-state      => 'disabled'
    );
    $butt{5} = $buttons->Button(-text       => 'Printer editor',
				-width      => 14,
				-command    => sub{system("$bin_dir/xedit-prt");},
				-state      => 'disabled'
    );
    $butt{6} = $buttons->Button(-text       => 'Date/Time editor',
				-width      => 14,
				-command    => sub{system("$bin_dir/xedit-date");}
    );

    # Pack the buttons...
    foreach $i (0, 1, 2, 3, 4, 5, 6) {
	$butt{$i}->pack;
    }
}
